version: '3'

services:
  app:
    container_name: 'app_dashboard'
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
    ports:
      - "8095:3000"
    # command: npm install cookie-parser && npm start
    networks:
      - backend_network
  
volumes:
  node_modules:

networks:
  backend_network:
    driver: bridge
