version: '3'

services:
  app:
    container_name: 'server_transaksi'
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - PORT=4000
    ports:
      - "7001:4000"
    # command: npm install cookie-parser && npm start
    networks:
      - apps_network
  
volumes:
  node_modules:

networks:
  backend_network:
    driver: bridge
