version: '3.8'

services:
  dashboard:
    image: docker.io/library/dashboard_valet_v2
    ports:
      - "7099:3000"
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge
