version: '3'

services:
  app:
    container_name: 'dashboard_v2_valet'
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - PORT=4000
    ports:
      - "7001:4000"
    command: npm run dev
    networks:
      - backend_network
  
volumes:
  node_modules:

networks:
  backend_network:
    driver: bridge
